/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package saberapp.client.professor.vistes;

/**
 *
 * @author Montse
 */
public class PM02Menu extends javax.swing.JFrame {

    /**
     * Creates new form PM02Menu
     */
    public PM02Menu() {
        initComponents();
        this.setSize(750, 600);
        this.setLocationRelativeTo(this);
        this.btInici.setSelected(true);

        jPanel1.setSize(750, 600);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        jPanelBarraSup = new javax.swing.JPanel();
        lbUsuari = new javax.swing.JLabel();
        lbLogout = new javax.swing.JLabel();
        btMenu = new javax.swing.JButton();
        jPanelEsqLlisc = new javax.swing.JPanel();
        btInici = new javax.swing.JButton();
        btUsuaris = new javax.swing.JButton();
        btRanquing = new javax.swing.JButton();
        btJoc = new javax.swing.JButton();
        jPanelPrinc = new javax.swing.JPanel();
        lbBenvinguts = new javax.swing.JLabel();
        lbLogo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(162, 215, 41));
        jPanel1.setMinimumSize(new java.awt.Dimension(750, 600));
        jPanel1.setName(""); // NOI18N
        jPanel1.setPreferredSize(new java.awt.Dimension(750, 600));
        jPanel1.setLayout(new java.awt.GridBagLayout());

        jPanelBarraSup.setBackground(new java.awt.Color(251, 139, 36));
        jPanelBarraSup.setPreferredSize(new java.awt.Dimension(396, 86));

        lbUsuari.setFont(new java.awt.Font("Raleway", 0, 14)); // NOI18N
        lbUsuari.setIcon(new javax.swing.ImageIcon(getClass().getResource("/saberapp/client/professor/vistes/recursos/icon_rounded_user_login.png"))); // NOI18N
        lbUsuari.setText("nomUser");
        lbUsuari.setIconTextGap(15);

        lbLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/saberapp/client/professor/vistes/recursos/icon_exit2_64.png"))); // NOI18N
        lbLogout.setToolTipText("Logout");
        lbLogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbLogoutMouseClicked(evt);
            }
        });

        btMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/saberapp/client/professor/vistes/recursos/icon_menu_64.png"))); // NOI18N
        btMenu.setBorderPainted(false);
        btMenu.setContentAreaFilled(false);
        btMenu.setFocusPainted(false);
        btMenu.setMaximumSize(new java.awt.Dimension(64, 64));
        btMenu.setMinimumSize(new java.awt.Dimension(64, 64));
        btMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btMenuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelBarraSupLayout = new javax.swing.GroupLayout(jPanelBarraSup);
        jPanelBarraSup.setLayout(jPanelBarraSupLayout);
        jPanelBarraSupLayout.setHorizontalGroup(
            jPanelBarraSupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBarraSupLayout.createSequentialGroup()
                .addComponent(btMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 333, Short.MAX_VALUE)
                .addComponent(lbUsuari, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lbLogout)
                .addContainerGap())
        );
        jPanelBarraSupLayout.setVerticalGroup(
            jPanelBarraSupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBarraSupLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelBarraSupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbLogout)
                    .addComponent(lbUsuari))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelBarraSupLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.FIRST_LINE_START;
        gridBagConstraints.weightx = 0.9;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 1);
        jPanel1.add(jPanelBarraSup, gridBagConstraints);

        jPanelEsqLlisc.setBackground(new java.awt.Color(239, 247, 207));

        btInici.setBackground(new java.awt.Color(209, 217, 177));
        btInici.setFont(new java.awt.Font("Raleway", 0, 12)); // NOI18N
        btInici.setText("Inici");
        btInici.setToolTipText("");
        btInici.setBorderPainted(false);
        btInici.setContentAreaFilled(false);
        btInici.setFocusPainted(false);
        btInici.setMaximumSize(new java.awt.Dimension(150, 25));
        btInici.setMinimumSize(new java.awt.Dimension(150, 25));
        btInici.setOpaque(true);
        btInici.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btIniciMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btIniciMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btIniciMouseExited(evt);
            }
        });

        btUsuaris.setBackground(new java.awt.Color(209, 217, 177));
        btUsuaris.setFont(new java.awt.Font("Raleway", 0, 12)); // NOI18N
        btUsuaris.setText("Usuaris");
        btUsuaris.setToolTipText("");
        btUsuaris.setBorderPainted(false);
        btUsuaris.setContentAreaFilled(false);
        btUsuaris.setFocusPainted(false);
        btUsuaris.setMaximumSize(new java.awt.Dimension(150, 25));
        btUsuaris.setMinimumSize(new java.awt.Dimension(150, 25));
        btUsuaris.setOpaque(true);
        btUsuaris.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btUsuarisMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btUsuarisMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btUsuarisMouseExited(evt);
            }
        });

        btRanquing.setBackground(new java.awt.Color(209, 217, 177));
        btRanquing.setFont(new java.awt.Font("Raleway", 0, 12)); // NOI18N
        btRanquing.setText("Rànquing");
        btRanquing.setToolTipText("");
        btRanquing.setBorderPainted(false);
        btRanquing.setContentAreaFilled(false);
        btRanquing.setFocusPainted(false);
        btRanquing.setMaximumSize(new java.awt.Dimension(150, 25));
        btRanquing.setMinimumSize(new java.awt.Dimension(150, 25));
        btRanquing.setOpaque(true);
        btRanquing.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btRanquingMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btRanquingMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btRanquingMouseExited(evt);
            }
        });

        btJoc.setBackground(new java.awt.Color(209, 217, 177));
        btJoc.setFont(new java.awt.Font("Raleway", 0, 12)); // NOI18N
        btJoc.setText("Joc");
        btJoc.setToolTipText("");
        btJoc.setBorderPainted(false);
        btJoc.setContentAreaFilled(false);
        btJoc.setFocusPainted(false);
        btJoc.setMaximumSize(new java.awt.Dimension(150, 25));
        btJoc.setMinimumSize(new java.awt.Dimension(150, 25));
        btJoc.setOpaque(true);
        btJoc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btJocMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btJocMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btJocMouseExited(evt);
            }
        });
        btJoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btJocActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelEsqLliscLayout = new javax.swing.GroupLayout(jPanelEsqLlisc);
        jPanelEsqLlisc.setLayout(jPanelEsqLliscLayout);
        jPanelEsqLliscLayout.setHorizontalGroup(
            jPanelEsqLliscLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btInici, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btUsuaris, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btRanquing, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
            .addComponent(btJoc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanelEsqLliscLayout.setVerticalGroup(
            jPanelEsqLliscLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelEsqLliscLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(btInici, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btUsuaris, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btRanquing, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btJoc, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weighty = 0.2;
        jPanel1.add(jPanelEsqLlisc, gridBagConstraints);

        jPanelPrinc.setBackground(new java.awt.Color(162, 215, 41));
        jPanelPrinc.setLayout(new javax.swing.BoxLayout(jPanelPrinc, javax.swing.BoxLayout.LINE_AXIS));

        lbBenvinguts.setFont(new java.awt.Font("Raleway", 1, 30)); // NOI18N
        lbBenvinguts.setText("Benvinguts");
        jPanelPrinc.add(lbBenvinguts);

        lbLogo.setFont(new java.awt.Font("Trebuchet MS", 1, 36)); // NOI18N
        lbLogo.setForeground(new java.awt.Color(23, 33, 33));
        lbLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/saberapp/client/professor/vistes/recursos/icon_logo_saberapp_64.png"))); // NOI18N
        lbLogo.setText("SaberApp");
        jPanelPrinc.add(lbLogo);

        jPanel1.add(jPanelPrinc, new java.awt.GridBagConstraints());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btJocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btJocActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btJocActionPerformed

    private void lbLogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbLogoutMouseClicked
        System.exit(0);
    }//GEN-LAST:event_lbLogoutMouseClicked

    private void btIniciMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btIniciMouseEntered
        btInici.setBackground(new java.awt.Color(189, 197, 157));
        btInici.setForeground(new java.awt.Color(239, 247, 207));
    }//GEN-LAST:event_btIniciMouseEntered

    private void btIniciMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btIniciMouseExited
        btInici.setBackground(new java.awt.Color(209, 217, 177));
        btInici.setForeground(new java.awt.Color(23, 33, 33));
    }//GEN-LAST:event_btIniciMouseExited

    private void btUsuarisMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btUsuarisMouseEntered
        btUsuaris.setBackground(new java.awt.Color(189, 197, 157));
        btUsuaris.setForeground(new java.awt.Color(239, 247, 207));
    }//GEN-LAST:event_btUsuarisMouseEntered

    private void btUsuarisMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btUsuarisMouseExited
        btUsuaris.setBackground(new java.awt.Color(209, 217, 177));
        btUsuaris.setForeground(new java.awt.Color(23, 33, 33));
    }//GEN-LAST:event_btUsuarisMouseExited

    private void btRanquingMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btRanquingMouseEntered
        btRanquing.setBackground(new java.awt.Color(189, 197, 157));
        btRanquing.setForeground(new java.awt.Color(239, 247, 207));
    }//GEN-LAST:event_btRanquingMouseEntered

    private void btRanquingMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btRanquingMouseExited
        btRanquing.setBackground(new java.awt.Color(209, 217, 177));
        btRanquing.setForeground(new java.awt.Color(23, 33, 33));
    }//GEN-LAST:event_btRanquingMouseExited

    private void btJocMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btJocMouseClicked
        
    }//GEN-LAST:event_btJocMouseClicked

    private void btJocMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btJocMouseEntered
        btJoc.setBackground(new java.awt.Color(189, 197, 157));
        btJoc.setForeground(new java.awt.Color(239, 247, 207));
    }//GEN-LAST:event_btJocMouseEntered

    private void btJocMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btJocMouseExited
        btJoc.setBackground(new java.awt.Color(209, 217, 177));
        btJoc.setForeground(new java.awt.Color(23, 33, 33));
    }//GEN-LAST:event_btJocMouseExited

    private void btIniciMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btIniciMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btIniciMouseClicked

    private void btUsuarisMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btUsuarisMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btUsuarisMouseClicked

    private void btRanquingMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btRanquingMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btRanquingMouseClicked

    private void btMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btMenuActionPerformed
        int position = this.jPanelEsqLlisc.getX();
        if(position > -1){
            Animacion.Animacion.mover_izquierda(0, -150, 2, 2, jPanelEsqLlisc);
        }else{
            Animacion.Animacion.mover_derecha(-150, 0, 2, 2, jPanelEsqLlisc);
        }
    }//GEN-LAST:event_btMenuActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PM02Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PM02Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PM02Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PM02Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PM02Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btInici;
    private javax.swing.JButton btJoc;
    private javax.swing.JButton btMenu;
    private javax.swing.JButton btRanquing;
    private javax.swing.JButton btUsuaris;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelBarraSup;
    private javax.swing.JPanel jPanelEsqLlisc;
    private javax.swing.JPanel jPanelPrinc;
    private javax.swing.JLabel lbBenvinguts;
    private javax.swing.JLabel lbLogo;
    private javax.swing.JLabel lbLogout;
    private javax.swing.JLabel lbUsuari;
    // End of variables declaration//GEN-END:variables
}
