/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package saberapp.client.professor.vistes;

import static java.awt.image.ImageObserver.WIDTH;
import java.io.DataInputStream;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import saberapp.client.professor.gestors.GestorClientProfessor;

/**
 *
 * @author Montse
 */
public class PM03Register extends javax.swing.JFrame {

    GestorClientProfessor controlador = new GestorClientProfessor();

    String nick, password, name, surname, mail, school, subject, image;

    boolean dadesOK = false;

    /**
     * Creates new form PM03Register
     *
     * @throws java.io.IOException
     */
    public PM03Register() throws IOException {

        initComponents();
        setSize(750, 625);
        setResizable(false);
        setLocationRelativeTo(null);

        jPanel1.setSize(750, 625);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lbIcona = new javax.swing.JLabel();
        lbUsuari = new javax.swing.JLabel();
        user = new javax.swing.JTextField();
        lbContrasenya = new javax.swing.JLabel();
        pass = new javax.swing.JPasswordField();
        btRegistrar = new javax.swing.JButton();
        lbCorreu = new javax.swing.JLabel();
        email = new javax.swing.JTextField();
        lbMateria = new javax.swing.JLabel();
        insti = new javax.swing.JTextField();
        lbInsti = new javax.swing.JLabel();
        cbMateria = new javax.swing.JComboBox<>();
        lbLogo = new javax.swing.JLabel();
        lbNom = new javax.swing.JLabel();
        nom = new javax.swing.JTextField();
        cognoms = new javax.swing.JTextField();
        lbCognoms = new javax.swing.JLabel();
        lbImatge = new javax.swing.JLabel();
        imatge = new javax.swing.JTextField();
        lbTornar = new javax.swing.JLabel();
        lbExit = new javax.swing.JLabel();
        lbMinim = new javax.swing.JLabel();
        lbTornarText = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(162, 215, 41));
        jPanel1.setMinimumSize(new java.awt.Dimension(750, 600));
        jPanel1.setPreferredSize(new java.awt.Dimension(750, 600));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbIcona.setIcon(new javax.swing.ImageIcon(getClass().getResource("/saberapp/client/professor/vistes/recursos/icon_rounded_user_login.png"))); // NOI18N
        jPanel1.add(lbIcona, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, -1, -1));

        lbUsuari.setFont(new java.awt.Font("Raleway", 1, 14)); // NOI18N
        lbUsuari.setText("*Usuari:");
        jPanel1.add(lbUsuari, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 110, -1, -1));

        user.setBackground(new java.awt.Color(239, 247, 207));
        user.setToolTipText("nom usuari");
        user.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userActionPerformed(evt);
            }
        });
        jPanel1.add(user, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 100, 200, 30));

        lbContrasenya.setFont(new java.awt.Font("Raleway", 1, 14)); // NOI18N
        lbContrasenya.setText("*Contrasenya:");
        jPanel1.add(lbContrasenya, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 150, -1, -1));

        pass.setBackground(new java.awt.Color(239, 247, 207));
        pass.setToolTipText("jPasswo");
        jPanel1.add(pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 140, 150, 30));

        btRegistrar.setFont(new java.awt.Font("Raleway", 0, 14)); // NOI18N
        btRegistrar.setText("Registrar");
        btRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRegistrarActionPerformed(evt);
            }
        });
        jPanel1.add(btRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 440, 100, 30));

        lbCorreu.setFont(new java.awt.Font("Raleway", 1, 14)); // NOI18N
        lbCorreu.setText("*Adreça electrònica:");
        jPanel1.add(lbCorreu, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 350, -1, -1));

        email.setBackground(new java.awt.Color(239, 247, 207));
        email.setToolTipText("nom usuari");
        email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailActionPerformed(evt);
            }
        });
        jPanel1.add(email, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 370, 260, 30));

        lbMateria.setFont(new java.awt.Font("Raleway", 1, 14)); // NOI18N
        lbMateria.setText("Matèria:");
        jPanel1.add(lbMateria, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 290, -1, -1));

        insti.setBackground(new java.awt.Color(239, 247, 207));
        insti.setToolTipText("nom usuari");
        insti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                instiActionPerformed(evt);
            }
        });
        jPanel1.add(insti, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 250, 260, 30));

        lbInsti.setFont(new java.awt.Font("Raleway", 1, 14)); // NOI18N
        lbInsti.setText("Centre educatiu:");
        jPanel1.add(lbInsti, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 230, -1, -1));

        cbMateria.setBackground(new java.awt.Color(239, 247, 207));
        cbMateria.setFont(new java.awt.Font("Raleway", 0, 12)); // NOI18N
        cbMateria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Art", "Mates", "Filo", "English" }));
        jPanel1.add(cbMateria, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 310, 260, 30));

        lbLogo.setFont(new java.awt.Font("Trebuchet MS", 1, 36)); // NOI18N
        lbLogo.setForeground(new java.awt.Color(251, 139, 36));
        lbLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/saberapp/client/professor/vistes/recursos/icon_logo_saberapp_64.png"))); // NOI18N
        lbLogo.setText("SaberApp");
        jPanel1.add(lbLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 510, -1, 70));

        lbNom.setFont(new java.awt.Font("Raleway", 1, 14)); // NOI18N
        lbNom.setText("Nom:");
        jPanel1.add(lbNom, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 230, -1, -1));

        nom.setBackground(new java.awt.Color(239, 247, 207));
        nom.setToolTipText("nom usuari");
        nom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomActionPerformed(evt);
            }
        });
        jPanel1.add(nom, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 250, 260, 30));

        cognoms.setBackground(new java.awt.Color(239, 247, 207));
        cognoms.setToolTipText("nom usuari");
        cognoms.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cognomsActionPerformed(evt);
            }
        });
        jPanel1.add(cognoms, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 310, 260, 30));

        lbCognoms.setFont(new java.awt.Font("Raleway", 1, 14)); // NOI18N
        lbCognoms.setText("Cognoms:");
        jPanel1.add(lbCognoms, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 290, -1, -1));

        lbImatge.setFont(new java.awt.Font("Raleway", 1, 14)); // NOI18N
        lbImatge.setText("Imatge:");
        jPanel1.add(lbImatge, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 350, -1, -1));

        imatge.setBackground(new java.awt.Color(239, 247, 207));
        imatge.setToolTipText("nom usuari");
        imatge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                imatgeActionPerformed(evt);
            }
        });
        jPanel1.add(imatge, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 370, 260, 30));

        lbTornar.setFont(new java.awt.Font("Raleway", 1, 36)); // NOI18N
        lbTornar.setText("<-");
        lbTornar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbTornarMouseClicked(evt);
            }
        });
        jPanel1.add(lbTornar, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 530, -1, -1));

        lbExit.setFont(new java.awt.Font("Raleway", 1, 18)); // NOI18N
        lbExit.setText("x");
        lbExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbExitMouseClicked(evt);
            }
        });
        jPanel1.add(lbExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 20, -1, -1));

        lbMinim.setFont(new java.awt.Font("Raleway", 1, 36)); // NOI18N
        lbMinim.setText("-");
        lbMinim.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbMinimMouseClicked(evt);
            }
        });
        jPanel1.add(lbMinim, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 10, -1, -1));

        lbTornarText.setFont(new java.awt.Font("Raleway", 0, 11)); // NOI18N
        lbTornarText.setText("TORNAR");
        jPanel1.add(lbTornarText, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 520, -1, -1));

        jLabel1.setFont(new java.awt.Font("Raleway", 0, 11)); // NOI18N
        jLabel1.setText("* Aquests camps són obligatoris");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 480, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void userActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userActionPerformed

    private void btRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRegistrarActionPerformed
        try {

            System.out.println("Iniciant Client Professor\n");
            controlador.startClient();

            controlador.sortidaClient.writeUTF("2");
            controlador.entradaClient = new DataInputStream(controlador.cs.getInputStream());
            String line = controlador.entradaClient.readUTF();
            System.out.println("Server Message: " + line);
            registrarUsuari();

        } catch (IOException ex) {
            Logger.getLogger(PM03Register.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btRegistrarActionPerformed

    private void emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailActionPerformed

    private void instiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_instiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_instiActionPerformed

    private void nomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomActionPerformed

    private void cognomsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cognomsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cognomsActionPerformed

    private void imatgeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_imatgeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_imatgeActionPerformed

    private void lbTornarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbTornarMouseClicked
        PM01Login f1 = new PM01Login();
        f1.setVisible(true);
        f1.pack();
        f1.setLocationRelativeTo(null);
        f1.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_lbTornarMouseClicked

    private void lbExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbExitMouseClicked
        System.exit(0);
    }//GEN-LAST:event_lbExitMouseClicked

    private void lbMinimMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbMinimMouseClicked
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_lbMinimMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PM03Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PM03Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PM03Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PM03Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new PM03Register().setVisible(true);
                } catch (IOException ex) {
                    Logger.getLogger(PM03Register.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btRegistrar;
    private javax.swing.JComboBox<String> cbMateria;
    private javax.swing.JTextField cognoms;
    private javax.swing.JTextField email;
    private javax.swing.JTextField imatge;
    private javax.swing.JTextField insti;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbCognoms;
    private javax.swing.JLabel lbContrasenya;
    private javax.swing.JLabel lbCorreu;
    private javax.swing.JLabel lbExit;
    private javax.swing.JLabel lbIcona;
    private javax.swing.JLabel lbImatge;
    private javax.swing.JLabel lbInsti;
    private javax.swing.JLabel lbLogo;
    private javax.swing.JLabel lbMateria;
    private javax.swing.JLabel lbMinim;
    private javax.swing.JLabel lbNom;
    private javax.swing.JLabel lbTornar;
    private javax.swing.JLabel lbTornarText;
    private javax.swing.JLabel lbUsuari;
    private javax.swing.JTextField nom;
    private javax.swing.JPasswordField pass;
    private javax.swing.JTextField user;
    // End of variables declaration//GEN-END:variables

    private void registrarUsuari() throws IOException {
        //TODO comprovar dades, return dades ok true

        nick = user.getText();
        password = pass.toString();
        name = nom.getText();
        surname = cognoms.getText();
        mail = email.getText();
        school = insti.getText();
        subject = cbMateria.getItemAt(WIDTH);
        image = imatge.getText();

        //Pattern p = Pattern.compile("^([0-9a-zA-Z]([_.w]*[0-9a-zA-Z])*@([0-9a-zA-Z][-w]*[0-9a-zA-Z].)+([a-zA-Z]{2,9}.)+[a-zA-Z]{2,3})$");
        //Matcher m = p.matcher(mail);
        //Validar dades
        //TODO millorar validació
        if (nick.isEmpty() || mail.isEmpty() || password.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Hi ha camps obligatoris buits", "Alerta", JOptionPane.WARNING_MESSAGE);

        } else {
            GestorClientProfessor controlador = new GestorClientProfessor();

            System.out.println("Iniciant Client Professor\n");
            try {
                dadesOK = true;

                controlador.sortidaClient.writeUTF(nick);
                controlador.sortidaClient.writeUTF(password);
                controlador.sortidaClient.writeUTF(name);
                controlador.sortidaClient.writeUTF(surname);

                controlador.sortidaClient.writeUTF(mail);
                controlador.sortidaClient.writeUTF(image);
                controlador.sortidaClient.writeInt(1);
                controlador.sortidaClient.writeUTF(subject);

                controlador.entradaClient = new DataInputStream(controlador.cs.getInputStream());
                String line = controlador.entradaClient.readUTF();
                System.out.println("Server Message: " + line);
                //1- tot correcte, 2-error en algun camp, 3-error
            } catch (IOException ex) {
                Logger.getLogger(PM03Register.class.getName()).log(Level.SEVERE, null, ex);
            } finally {
                controlador.cs.close();
            }

        }
        if (dadesOK) {
            PM02Menu f2 = new PM02Menu();
            f2.setVisible(true);
            this.dispose();
        } else {
            JOptionPane.showMessageDialog(null, "Omple tots els camps obligatòris \nIntenta-ho de nou", "Error", JOptionPane.ERROR_MESSAGE);
        }

    }
}
