/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistes;

import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Montse
 */
public class PM01Login extends javax.swing.JFrame {

    String contrasenya;
    String nick;

    /**
     * Creates new form PM01Login
     */
    public PM01Login() {
        initComponents();
        setSize(500, 475);
        setResizable(false);
        setLocationRelativeTo(null);

        jPanel1.setSize(500, 475);
    }

    public void validarUsuari() {

        contrasenya = new String(pass.getPassword());
        nick = user.getText();

        //TO DO Connectar, buscar i retornar
        /*
        try{
            Connection cs=DriverManager.getConnection("jdbc:mysql://localhost/mydb1","root","1234");
            PreparedStatement sp=cs.prepareStatement("select * from mytab1");
            ResultSet rs=sp.executeQuery("select * from mytab1 where
            username='"+search.getText()+"'");
            while (rs.next()){
                user.setText(rs.getString(1));
                pass.setText(rs.getString(2));
                country.setText(rs.getString(3));
                district.setText(rs.getString(4));
            }
            JOptionPane.showMessageDialog(this,"Searched");
        }catch (Exception ex){
            JOptionPane.showMessageDialog(this,ex.getMessage());
        } 
        */
        
        if (user.getText().equals("Eduard") && contrasenya.compareTo("1234") == 0) { //TO DO canviar if usuari existeix

            dispose();
            PM02Menu f2 = new PM02Menu();
            f2.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(null, "Usuari o contrasenya incorrecta \nIntenta-ho de nou", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lbIcona = new javax.swing.JLabel();
        lbPassword = new javax.swing.JLabel();
        lbUser = new javax.swing.JLabel();
        user = new javax.swing.JTextField();
        pass = new javax.swing.JPasswordField();
        btLogin = new javax.swing.JButton();
        lbRegister = new javax.swing.JLabel();
        lbLogo = new javax.swing.JLabel();
        lbExit = new javax.swing.JLabel();
        lbMinim = new javax.swing.JLabel();
        lbOblit = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(162, 215, 41));
        jPanel1.setMinimumSize(new java.awt.Dimension(500, 450));
        jPanel1.setPreferredSize(new java.awt.Dimension(500, 450));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbIcona.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/icon_account_login_enter_door.png"))); // NOI18N
        jPanel1.add(lbIcona, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 40, -1, -1));

        lbPassword.setFont(new java.awt.Font("Raleway", 1, 14)); // NOI18N
        lbPassword.setText("Contrasenya:");
        jPanel1.add(lbPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 190, -1, -1));

        lbUser.setFont(new java.awt.Font("Raleway", 1, 14)); // NOI18N
        lbUser.setText("Usuari:");
        jPanel1.add(lbUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 120, -1, -1));

        user.setBackground(new java.awt.Color(239, 247, 207));
        user.setToolTipText("nom usuari");
        user.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userActionPerformed(evt);
            }
        });
        jPanel1.add(user, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 150, 200, 30));

        pass.setBackground(new java.awt.Color(239, 247, 207));
        pass.setToolTipText("contrasenya");
        jPanel1.add(pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 220, 200, 30));

        btLogin.setFont(new java.awt.Font("Raleway", 1, 14)); // NOI18N
        btLogin.setText("Entrar");
        btLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLoginActionPerformed(evt);
            }
        });
        jPanel1.add(btLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 220, 90, 30));

        lbRegister.setFont(new java.awt.Font("Raleway", 1, 14)); // NOI18N
        lbRegister.setForeground(new java.awt.Color(251, 139, 36));
        lbRegister.setText("Encara no ets usuari? Registra't");
        lbRegister.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbRegisterMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbRegisterMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbRegisterMouseExited(evt);
            }
        });
        jPanel1.add(lbRegister, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 290, -1, -1));

        lbLogo.setFont(new java.awt.Font("Trebuchet MS", 1, 36)); // NOI18N
        lbLogo.setForeground(new java.awt.Color(251, 139, 36));
        lbLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/icon_logo_saberapp_64.png"))); // NOI18N
        lbLogo.setText("SaberApp");
        jPanel1.add(lbLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 370, -1, -1));

        lbExit.setFont(new java.awt.Font("Raleway", 1, 18)); // NOI18N
        lbExit.setText("x");
        lbExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbExitMouseClicked(evt);
            }
        });
        jPanel1.add(lbExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 20, -1, -1));

        lbMinim.setFont(new java.awt.Font("Raleway", 1, 36)); // NOI18N
        lbMinim.setText("-");
        lbMinim.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbMinimMouseClicked(evt);
            }
        });
        jPanel1.add(lbMinim, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 10, -1, -1));

        lbOblit.setFont(new java.awt.Font("Raleway", 0, 10)); // NOI18N
        lbOblit.setText("Si has oblidat l'usuari o contrasenya, posa't en contacte amb l'administrador");
        lbOblit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbOblitMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbOblitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbOblitMouseExited(evt);
            }
        });
        jPanel1.add(lbOblit, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 320, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void userActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userActionPerformed

    private void btLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLoginActionPerformed
        validarUsuari();
    }//GEN-LAST:event_btLoginActionPerformed

    private void lbRegisterMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbRegisterMouseEntered
        lbRegister.setFont(new java.awt.Font("Raleway", 1, 18));
        lbRegister.setForeground(new java.awt.Color(23, 33, 33));
    }//GEN-LAST:event_lbRegisterMouseEntered

    private void lbRegisterMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbRegisterMouseExited
        lbRegister.setFont(new java.awt.Font("Raleway", 1, 14));
        lbRegister.setForeground(new java.awt.Color(251, 139, 36));
    }//GEN-LAST:event_lbRegisterMouseExited

    private void lbRegisterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbRegisterMouseClicked
        PM03Register f3 = new PM03Register();
        f3.setVisible(true);
        f3.setLocationRelativeTo(null);
        f3.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_lbRegisterMouseClicked

    private void lbMinimMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbMinimMouseClicked
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_lbMinimMouseClicked

    private void lbExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbExitMouseClicked
        System.exit(0);
    }//GEN-LAST:event_lbExitMouseClicked

    private void lbOblitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbOblitMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lbOblitMouseClicked

    private void lbOblitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbOblitMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_lbOblitMouseEntered

    private void lbOblitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbOblitMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_lbOblitMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PM01Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PM01Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PM01Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PM01Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PM01Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btLogin;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbExit;
    private javax.swing.JLabel lbIcona;
    private javax.swing.JLabel lbLogo;
    private javax.swing.JLabel lbMinim;
    private javax.swing.JLabel lbOblit;
    private javax.swing.JLabel lbPassword;
    private javax.swing.JLabel lbRegister;
    private javax.swing.JLabel lbUser;
    private javax.swing.JPasswordField pass;
    private javax.swing.JTextField user;
    // End of variables declaration//GEN-END:variables
}
