/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package paquet1;

import javax.swing.JOptionPane;

/**
 *
 * @author Montse
 */
public class PM01Login extends javax.swing.JFrame {

    String contrasenya;

    /**
     * Creates new form PM01Login
     */
    public PM01Login() {
        initComponents();
        setSize(500, 450);
        setResizable(false);
        setLocationRelativeTo(null);

        jPanel1.setSize(500, 450);
    }

    public void validarUsuari() {

        contrasenya = new String(pass.getPassword());

        if (user.getText().equals("Eduard") && contrasenya.compareTo("1234") == 0) {

            dispose();
            PM02Menu f2 = new PM02Menu();
            f2.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(null, "Usuari o contrasenya incorrecta \nIntenta-ho de nou", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lbIcona = new javax.swing.JLabel();
        lbPassword = new javax.swing.JLabel();
        lbUser = new javax.swing.JLabel();
        user = new javax.swing.JTextField();
        pass = new javax.swing.JPasswordField();
        btLogin = new javax.swing.JButton();
        lbRegister = new javax.swing.JLabel();
        lbLogo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(162, 215, 41));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbIcona.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imatges/icon_login_account_enter_door.png"))); // NOI18N
        jPanel1.add(lbIcona, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 40, -1, -1));

        lbPassword.setFont(new java.awt.Font("Raleway", 1, 14)); // NOI18N
        lbPassword.setText("Contrasenya:");
        jPanel1.add(lbPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 190, -1, -1));

        lbUser.setFont(new java.awt.Font("Raleway", 1, 14)); // NOI18N
        lbUser.setText("Usuari:");
        jPanel1.add(lbUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 120, -1, -1));

        user.setBackground(new java.awt.Color(239, 247, 207));
        user.setToolTipText("nom usuari");
        user.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userActionPerformed(evt);
            }
        });
        jPanel1.add(user, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 150, 200, 30));

        pass.setBackground(new java.awt.Color(239, 247, 207));
        pass.setToolTipText("contrasenya");
        jPanel1.add(pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 220, 200, 30));

        btLogin.setFont(new java.awt.Font("Raleway", 1, 14)); // NOI18N
        btLogin.setText("Entrar");
        btLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLoginActionPerformed(evt);
            }
        });
        jPanel1.add(btLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 220, 90, 30));

        lbRegister.setFont(new java.awt.Font("Raleway", 1, 14)); // NOI18N
        lbRegister.setForeground(new java.awt.Color(251, 139, 36));
        lbRegister.setText("Encara no ets usuari? Registra't");
        lbRegister.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbRegisterMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbRegisterMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbRegisterMouseExited(evt);
            }
        });
        jPanel1.add(lbRegister, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 290, -1, -1));

        lbLogo.setFont(new java.awt.Font("Trebuchet MS", 1, 36)); // NOI18N
        lbLogo.setForeground(new java.awt.Color(251, 139, 36));
        lbLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imatges/iconfinder_242-Data_2124160.png"))); // NOI18N
        lbLogo.setText("SaberApp");
        jPanel1.add(lbLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 330, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void userActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userActionPerformed

    private void btLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLoginActionPerformed
        validarUsuari();
    }//GEN-LAST:event_btLoginActionPerformed

    private void lbRegisterMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbRegisterMouseEntered
        lbRegister.setFont(new java.awt.Font("Raleway", 1, 18));
        lbRegister.setForeground(new java.awt.Color(23, 33, 33));
    }//GEN-LAST:event_lbRegisterMouseEntered

    private void lbRegisterMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbRegisterMouseExited
        lbRegister.setFont(new java.awt.Font("Raleway", 1, 14)); 
        lbRegister.setForeground(new java.awt.Color(251, 139, 36));
    }//GEN-LAST:event_lbRegisterMouseExited

    private void lbRegisterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbRegisterMouseClicked
        dispose();
        PM03Register f3 = new PM03Register();
        f3.setVisible(true);
    }//GEN-LAST:event_lbRegisterMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PM01Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PM01Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PM01Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PM01Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PM01Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btLogin;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbIcona;
    private javax.swing.JLabel lbLogo;
    private javax.swing.JLabel lbPassword;
    private javax.swing.JLabel lbRegister;
    private javax.swing.JLabel lbUser;
    private javax.swing.JPasswordField pass;
    private javax.swing.JTextField user;
    // End of variables declaration//GEN-END:variables
}
