/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package paquet1;

/**
 *
 * @author Montse
 */
public class PM02Menu extends javax.swing.JFrame {

    /**
     * Creates new form PM02Menu
     */
    public PM02Menu() {
        initComponents();
        setSize(500, 450);
        setResizable(false);
        setLocationRelativeTo(null);

        jPanel1.setSize(500, 450);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lbBenvinguts = new javax.swing.JLabel();
        btSetGame = new javax.swing.JButton();
        btGestorUsuaris = new javax.swing.JButton();
        btRanking = new javax.swing.JButton();
        lbLogo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(162, 215, 41));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbBenvinguts.setFont(new java.awt.Font("Raleway", 1, 30)); // NOI18N
        lbBenvinguts.setText("Benvinguts");
        jPanel1.add(lbBenvinguts, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 140, -1, -1));

        btSetGame.setFont(new java.awt.Font("Raleway", 1, 14)); // NOI18N
        btSetGame.setText("Configura joc");
        btSetGame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSetGameActionPerformed(evt);
            }
        });
        jPanel1.add(btSetGame, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 140, 140, 30));

        btGestorUsuaris.setFont(new java.awt.Font("Raleway", 1, 14)); // NOI18N
        btGestorUsuaris.setText("Usuaris");
        btGestorUsuaris.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btGestorUsuarisActionPerformed(evt);
            }
        });
        jPanel1.add(btGestorUsuaris, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 100, 140, 30));

        btRanking.setFont(new java.awt.Font("Raleway", 1, 14)); // NOI18N
        btRanking.setText("Rànquings");
        btRanking.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRankingActionPerformed(evt);
            }
        });
        jPanel1.add(btRanking, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 180, 140, 30));

        lbLogo.setFont(new java.awt.Font("Trebuchet MS", 1, 36)); // NOI18N
        lbLogo.setForeground(new java.awt.Color(251, 139, 36));
        lbLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imatges/iconfinder_242-Data_2124160.png"))); // NOI18N
        lbLogo.setText("SaberApp");
        jPanel1.add(lbLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 330, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btSetGameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSetGameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btSetGameActionPerformed

    private void btGestorUsuarisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btGestorUsuarisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btGestorUsuarisActionPerformed

    private void btRankingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRankingActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btRankingActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PM02Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PM02Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PM02Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PM02Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PM02Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btGestorUsuaris;
    private javax.swing.JButton btRanking;
    private javax.swing.JButton btSetGame;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbBenvinguts;
    private javax.swing.JLabel lbLogo;
    // End of variables declaration//GEN-END:variables
}
